manifest_version = "1.1.2"

[compilers.cr1comp]
description = "Campbell Scientific CR1 Compiler"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr1comp.zip"
executable_name = "cr1comp.exe"
requires_wine = true
supported_loggers = [ "CR1",]
sha256 = "3a7ffd845280f8683acfe38e2b2556f696cee58041c6471e369bd43b101031dd"

[compilers.cr300comp]
description = "Campbell Scientific CR300 Compiler"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr300comp.zip"
executable_name = "cr300comp.exe"
requires_wine = true
supported_loggers = [ "CR300",]
sha256 = "60c96f28e652fad784962d82f62c00ff1fad4874172362c43e14342bdd7f4487"

[compilers.cr2comp]
description = "Campbell Scientific CR200 Compiler (Base Version)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2comp.zip"
executable_name = "cr2comp.exe"
requires_wine = true
supported_loggers = [ "CR200",]
sha256 = "eb3481f1f336f21769a710da2054b1d37fa27c2766387df0bef14a0d714529d9"

[compilers.cr5comp]
description = "Campbell Scientific Compiler (CR5COMP.EXE)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr5comp.zip"
executable_name = "CR5COMP.EXE"
requires_wine = true
supported_loggers = []
sha256 = "39a4bf5ccfb6e3c26f87c8d11e0c22a514388ba4e8f8bfab846ea26c34309eef"

[compilers.cr6comp]
description = "Campbell Scientific Compiler (CR6Comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr6comp.zip"
executable_name = "CR6Comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "2500c7637e35511505cc0216009dfc3d2c546901c3e5cca43f581148423adfcd"

[compilers.granite10comp]
description = "Campbell Scientific Compiler (Granite10Comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/granite10comp.zip"
executable_name = "Granite10Comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "a241deec5a95c02a2d86a75a0e7969ceb37d17f1bfdeb9b67d8342925eeb00a4"

[compilers.granite6comp]
description = "Campbell Scientific Compiler (Granite6Comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/granite6comp.zip"
executable_name = "Granite6Comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "ea9c58be884a977b24159056f709d559b533882a3ea5c78ebad6097615c1684e"

[compilers.granite9comp]
description = "Campbell Scientific Compiler (Granite9comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/granite9comp.zip"
executable_name = "Granite9comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "26c070165218d8a7060e0ed7d1f695f1377d87f5e5558860f6a13895544de98d"

[compilers.cr1000xcomp]
description = "Campbell Scientific Compiler (cr1000xcomp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr1000xcomp.zip"
executable_name = "cr1000xcomp.exe"
requires_wine = true
supported_loggers = []
sha256 = "2424acb6093064742ea5ef0ffb436afbf4b6cd7ea0032e7e7f328447ddf536e6"

[compilers.cr2compcr200x-std-00]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.00.exe)"
version = "std-00"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr200x-std-00.zip"
executable_name = "cr2compCR200X.Std.00.exe"
requires_wine = true
supported_loggers = []
sha256 = "63153607044425eb19954c473d59880649081e1ac45b9f147d3ecc792011da9e"

[compilers.cr2compcr200x-std-01]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.01.exe)"
version = "std-01"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr200x-std-01.zip"
executable_name = "cr2compCR200X.Std.01.exe"
requires_wine = true
supported_loggers = []
sha256 = "d616d5158d651c34a2447047b93218b2bb99b7bef11f5d8661bc6b0f4ca3c24a"

[compilers.cr2compcr200x-std-02]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.02.exe)"
version = "std-02"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr200x-std-02.zip"
executable_name = "cr2compCR200X.Std.02.exe"
requires_wine = true
supported_loggers = []
sha256 = "f8ea30f3677d70208db292dc8b74f90887f3e394ba6ea6cc3e311e8afda113bb"

[compilers.cr2compcr200x-std-03]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.03.exe)"
version = "std-03"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr200x-std-03.zip"
executable_name = "cr2compCR200X.Std.03.exe"
requires_wine = true
supported_loggers = []
sha256 = "9627e2eadbda86b4e9bf37a4bbe73173cbc05ff465f380f929963f7540e289dc"

[compilers.cr2compcr200x-std-04]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.04.exe)"
version = "std-04"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr200x-std-04.zip"
executable_name = "cr2compCR200X.Std.04.exe"
requires_wine = true
supported_loggers = []
sha256 = "4ea2850ca5dbf6da5ee8e9720c71b70f80c74e8554885a1341af423e5b66fff4"

[compilers.cr2compcr295x-std-00]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.00.exe)"
version = "std-00"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr295x-std-00.zip"
executable_name = "cr2compCR295X.Std.00.exe"
requires_wine = true
supported_loggers = []
sha256 = "78bb8632e8761d4b4bc0a3e7c357a3fb2af03d8231635a105c6d727af016288e"

[compilers.cr2compcr295x-std-01]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.01.exe)"
version = "std-01"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr295x-std-01.zip"
executable_name = "cr2compCR295X.Std.01.exe"
requires_wine = true
supported_loggers = []
sha256 = "3c1465c4822b28a499dc7543fef464876290528a06a6c97eb4a81cdb37340362"

[compilers.cr2compcr295x-std-02]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.02.exe)"
version = "std-02"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr295x-std-02.zip"
executable_name = "cr2compCR295X.Std.02.exe"
requires_wine = true
supported_loggers = []
sha256 = "ea9de4207632386a18b5cdc35e54e51b7504ca79b87abf7527c7577cd4921414"

[compilers.cr2compcr295x-std-03]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.03.exe)"
version = "std-03"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr295x-std-03.zip"
executable_name = "cr2compCR295X.Std.03.exe"
requires_wine = true
supported_loggers = []
sha256 = "e8e457d044de4a8693c34f413f9bcb4100f584db964c26b2625625c0d929c078"

[compilers.cr2compcr295x-std-04]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.04.exe)"
version = "std-04"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compcr295x-std-04.zip"
executable_name = "cr2compCR295X.Std.04.exe"
requires_wine = true
supported_loggers = []
sha256 = "a50c963421324fb7d3f8daad264bc1a10f8deeb18224aef6db0e026c1a45df8c"

[compilers.cr2compv0-2-01]
description = "Campbell Scientific Compiler (cr2compv0.2.01.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv0-2-01.zip"
executable_name = "cr2compv0.2.01.exe"
requires_wine = true
supported_loggers = []
sha256 = "acec3c48669c4feefe8dcf3e7b172a07a9ee620ebb95c018143980919f076c3f"

[compilers.cr2compv02]
description = "Campbell Scientific Compiler (cr2compv02.exe)"
version = "v02"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv02.zip"
executable_name = "cr2compv02.exe"
requires_wine = true
supported_loggers = []
sha256 = "cb330b46a219eacdaac1023616050f259fb89beddb79191ea6b25df2506d7476"

[compilers.cr2compv03a]
description = "Campbell Scientific Compiler (cr2compv03A.exe)"
version = "v03a"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv03a.zip"
executable_name = "cr2compv03A.exe"
requires_wine = true
supported_loggers = []
sha256 = "dbb524011e1b728f77cf8c98894eaccabf1bba686ba391d3a701ad2f93738d2c"

[compilers.cr2compv04]
description = "Campbell Scientific Compiler (cr2compv04.exe)"
version = "v04"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv04.zip"
executable_name = "cr2compv04.exe"
requires_wine = true
supported_loggers = []
sha256 = "b557091870338c0e935e12f019a5f9daa1dddf14533eff290880a26ccb1457b5"

[compilers.cr2compv04g]
description = "Campbell Scientific Compiler (cr2compv04G.exe)"
version = "v04g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv04g.zip"
executable_name = "cr2compv04G.exe"
requires_wine = true
supported_loggers = []
sha256 = "d10d48c2b43356228a4cef2193b25561251f7c37e198553a7995fa7a15db938c"

[compilers.cr2compv05]
description = "Campbell Scientific Compiler (cr2compv05.exe)"
version = "v05"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv05.zip"
executable_name = "cr2compv05.exe"
requires_wine = true
supported_loggers = []
sha256 = "14774b1db5ca8108a2c52e1dc50315784e3b05948d890b9f2cd4591a5276b782"

[compilers.cr2compv06]
description = "Campbell Scientific Compiler (cr2compv06.exe)"
version = "v06"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv06.zip"
executable_name = "cr2compv06.exe"
requires_wine = true
supported_loggers = []
sha256 = "af639f34a6f15d43cd2b140ce24406c30206902c5926b051a61ebaa8922366ad"

[compilers.cr2compv06g]
description = "Campbell Scientific Compiler (cr2compv06G.exe)"
version = "v06g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv06g.zip"
executable_name = "cr2compv06G.exe"
requires_wine = true
supported_loggers = []
sha256 = "768c6b0fd8171355b75bcaf312bad9e22232badcb5408412fa2e8083629f475c"

[compilers.cr2compv06s]
description = "Campbell Scientific Compiler (cr2compv06S.exe)"
version = "v06s"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv06s.zip"
executable_name = "cr2compv06S.exe"
requires_wine = true
supported_loggers = []
sha256 = "3d14a75b100f9a7d1fab764369f81e64c63d3cb1e2824632819f8c5eb9858b41"

[compilers.cr2compv07]
description = "Campbell Scientific Compiler (cr2compv07.exe)"
version = "v07"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv07.zip"
executable_name = "cr2compv07.exe"
requires_wine = true
supported_loggers = []
sha256 = "cf3af129d08652b94b763c7ec7c2a2bc595c3ebd25b63de144df274ebc14206d"

[compilers.cr2compv07g]
description = "Campbell Scientific Compiler (cr2compv07G.exe)"
version = "v07g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv07g.zip"
executable_name = "cr2compv07G.exe"
requires_wine = true
supported_loggers = []
sha256 = "3ba4061574b3a803dba257e68283d8d4e05a03244899d547c2b94f938d87d170"

[compilers.cr2compv07m]
description = "Campbell Scientific Compiler (cr2compv07M.exe)"
version = "v07m"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv07m.zip"
executable_name = "cr2compv07M.exe"
requires_wine = true
supported_loggers = []
sha256 = "46013df058ea49433da2701a242926b39fc7faebb659305b5a38ba60a83981ae"

[compilers.cr2compv07s]
description = "Campbell Scientific Compiler (cr2compv07S.exe)"
version = "v07s"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv07s.zip"
executable_name = "cr2compv07S.exe"
requires_wine = true
supported_loggers = []
sha256 = "7159b72d1f5d3103c34eabed6b193b0ecd1cf07707b639d35bf65397977c15a6"

[compilers.cr2compv09]
description = "Campbell Scientific Compiler (cr2compv09.exe)"
version = "v09"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv09.zip"
executable_name = "cr2compv09.exe"
requires_wine = true
supported_loggers = []
sha256 = "661d7ef2faa8454cbd21753b96c0cca01222e8376d213cf7c7a2b187d4d8f147"

[compilers.cr2compv09g]
description = "Campbell Scientific Compiler (cr2compv09G.exe)"
version = "v09g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv09g.zip"
executable_name = "cr2compv09G.exe"
requires_wine = true
supported_loggers = []
sha256 = "135bc4052e053f64b339566196664be67d0c45e20e66525fb00f041b710023c9"

[compilers.cr2compv09m]
description = "Campbell Scientific Compiler (cr2compv09M.exe)"
version = "v09m"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv09m.zip"
executable_name = "cr2compv09M.exe"
requires_wine = true
supported_loggers = []
sha256 = "afc2dc46e9ddf3ffac2b7f0dff0f148f0307dc881718dd2bd3b9ab2bea6b6e32"

[compilers.cr2compv09s]
description = "Campbell Scientific Compiler (cr2compv09S.exe)"
version = "v09s"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv09s.zip"
executable_name = "cr2compv09S.exe"
requires_wine = true
supported_loggers = []
sha256 = "ce1b837ae51abc9e80e55c3bb80650afe4c841df0b9061fd7f5b5a7de02089ba"

[compilers.cr2compv10]
description = "Campbell Scientific Compiler (cr2compv10.exe)"
version = "v10"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv10.zip"
executable_name = "cr2compv10.exe"
requires_wine = true
supported_loggers = []
sha256 = "e64bb8ec82c2b10c975302c18db53defa155e65096d88d2c4f15e878ca2c9bd0"

[compilers.cr2compv10g]
description = "Campbell Scientific Compiler (cr2compv10G.exe)"
version = "v10g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv10g.zip"
executable_name = "cr2compv10G.exe"
requires_wine = true
supported_loggers = []
sha256 = "4d4360442de2edaa5d29d713092bd3facd0b0ebdc3570594c1555f5bd155d3b5"

[compilers.cr2compv10m]
description = "Campbell Scientific Compiler (cr2compv10M.exe)"
version = "v10m"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv10m.zip"
executable_name = "cr2compv10M.exe"
requires_wine = true
supported_loggers = []
sha256 = "2ba52c51cfdbadc53341f6158734867088889794de86aaf35d7923cdf04218fc"

[compilers.cr2compv10s]
description = "Campbell Scientific Compiler (cr2compv10S.exe)"
version = "v10s"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr2compv10s.zip"
executable_name = "cr2compv10S.exe"
requires_wine = true
supported_loggers = []
sha256 = "bae4679374056cb9b044f1a54a19d21f96b4a2c3ee0193489f032833c747903a"

[compilers.cr350comp]
description = "Campbell Scientific Compiler (cr350comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr350comp.zip"
executable_name = "cr350comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "773338f7061e9d0242413b7f16ca754af3cd8c3140f7a2037839cfc9238f9cc7"

[compilers.cr3comp]
description = "Campbell Scientific Compiler (cr3comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr3comp.zip"
executable_name = "cr3comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "23a300f76c1c3ef7bc08e57db9a3288e411da4129914f16fd4f6177768145655"

[compilers.cr8comp]
description = "Campbell Scientific Compiler (cr8comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr8comp.zip"
executable_name = "cr8comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "0ee391214247d5a5ad4575c9f0c82dbbd8b49df71db46f51a35d430e28c230e9"

[compilers.cr9comp]
description = "Campbell Scientific Compiler (cr9comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/PLACEHOLDER_TAG/cr9comp.zip"
executable_name = "cr9comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "477535e3f327922e71dc562e0e64a7289ebd399b6d3d30d1a026409b357d5111"
