manifest_version = "2025.05.13.0"

[compilers.cr1comp]
description = "Campbell Scientific CR1 Compiler"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr1comp.zip"
executable_name = "cr1comp.exe"
requires_wine = true
supported_loggers = [ "CR1",]
sha256 = "73c92c82cda0805ea1593b414f6a545de17005fc73b7e2175fecaa7e1671b46a"

[compilers.cr300comp]
description = "Campbell Scientific CR300 Compiler"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr300comp.zip"
executable_name = "cr300comp.exe"
requires_wine = true
supported_loggers = [ "CR300",]
sha256 = "9ef0b9c08c747c45d11170a5695c86d1cfb10d46de91da0060254e5c6b03ae1e"

[compilers.cr2comp]
description = "Campbell Scientific CR200 Compiler (Base Version)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2comp.zip"
executable_name = "cr2comp.exe"
requires_wine = true
supported_loggers = [ "CR200",]
sha256 = "b4fe726d0f0a68dee31a2145a0ea6da8518044fc9a4f9ec9b3882805c62b23a2"

[compilers.cr5comp]
description = "Campbell Scientific Compiler (CR5COMP.EXE)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr5comp.zip"
executable_name = "CR5COMP.EXE"
requires_wine = true
supported_loggers = []
sha256 = "917788f7cbb4807344b8138cdf6d5e74361128202d70b9bb82dfd17b04caf545"

[compilers.cr6comp]
description = "Campbell Scientific Compiler (CR6Comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr6comp.zip"
executable_name = "CR6Comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "cb425b48b8e1f8081108fe5a1b98ca84ea5630a0122663aafcc0146adfc3a748"

[compilers.granite10comp]
description = "Campbell Scientific Compiler (Granite10Comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/granite10comp.zip"
executable_name = "Granite10Comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "b45817a8331515b4f1d98b8f611d2813b3b1bca21ea14e970c697b083ba07cc8"

[compilers.granite6comp]
description = "Campbell Scientific Compiler (Granite6Comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/granite6comp.zip"
executable_name = "Granite6Comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "5516480779059103deb79c7ddf1c3850e3a3c9845748a03e35496d407657eb56"

[compilers.granite9comp]
description = "Campbell Scientific Compiler (Granite9comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/granite9comp.zip"
executable_name = "Granite9comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "888b9c3457c0aa8539469aab09b31c3cb2f158b6dd9f625e258486f9c107d823"

[compilers.cr1000xcomp]
description = "Campbell Scientific Compiler (cr1000xcomp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr1000xcomp.zip"
executable_name = "cr1000xcomp.exe"
requires_wine = true
supported_loggers = []
sha256 = "92131fb10d533b3cb70a632fb0082543c0b4313ad41f17850f8650f1b05b3916"

[compilers.cr2compcr200x-std-00]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.00.exe)"
version = "std-00"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr200x-std-00.zip"
executable_name = "cr2compCR200X.Std.00.exe"
requires_wine = true
supported_loggers = []
sha256 = "84f31933b722849f06c33925952aa012333632d043d12821618a4b09c1c17604"

[compilers.cr2compcr200x-std-01]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.01.exe)"
version = "std-01"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr200x-std-01.zip"
executable_name = "cr2compCR200X.Std.01.exe"
requires_wine = true
supported_loggers = []
sha256 = "d78f158daff35bf7295e8c983f01f5c63aa80e5386abd251e70996d3de9a5c0d"

[compilers.cr2compcr200x-std-02]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.02.exe)"
version = "std-02"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr200x-std-02.zip"
executable_name = "cr2compCR200X.Std.02.exe"
requires_wine = true
supported_loggers = []
sha256 = "f6ffe0992763c37d58bd11844dec8464153f153cd0f2a2655569e49d63048aa2"

[compilers.cr2compcr200x-std-03]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.03.exe)"
version = "std-03"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr200x-std-03.zip"
executable_name = "cr2compCR200X.Std.03.exe"
requires_wine = true
supported_loggers = []
sha256 = "d9fd79a48b48fc3b739596ba7239bd31c80237887d577153d172818785a1e0f9"

[compilers.cr2compcr200x-std-04]
description = "Campbell Scientific Compiler (cr2compCR200X.Std.04.exe)"
version = "std-04"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr200x-std-04.zip"
executable_name = "cr2compCR200X.Std.04.exe"
requires_wine = true
supported_loggers = []
sha256 = "53d8ad678477cd733abce4520393167358d8f814e3ee1cc6822d7bbc6bce39eb"

[compilers.cr2compcr295x-std-00]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.00.exe)"
version = "std-00"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr295x-std-00.zip"
executable_name = "cr2compCR295X.Std.00.exe"
requires_wine = true
supported_loggers = []
sha256 = "aba1442db5494ebd89cd7de17276509fad3063182051dfb74457e72be1a96cfa"

[compilers.cr2compcr295x-std-01]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.01.exe)"
version = "std-01"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr295x-std-01.zip"
executable_name = "cr2compCR295X.Std.01.exe"
requires_wine = true
supported_loggers = []
sha256 = "d658aaa6ac687088561a67e397b7b237ddc0b7ee3298d1de121a688834e0df1f"

[compilers.cr2compcr295x-std-02]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.02.exe)"
version = "std-02"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr295x-std-02.zip"
executable_name = "cr2compCR295X.Std.02.exe"
requires_wine = true
supported_loggers = []
sha256 = "f9658b002873cd364d8a4cb7aee1b2e067bbec67d5ed2ab3011e9bf31854316e"

[compilers.cr2compcr295x-std-03]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.03.exe)"
version = "std-03"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr295x-std-03.zip"
executable_name = "cr2compCR295X.Std.03.exe"
requires_wine = true
supported_loggers = []
sha256 = "e9528b292b0ca1191f3151e1c7108e43528e92256c97be89081083fabe54c087"

[compilers.cr2compcr295x-std-04]
description = "Campbell Scientific Compiler (cr2compCR295X.Std.04.exe)"
version = "std-04"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compcr295x-std-04.zip"
executable_name = "cr2compCR295X.Std.04.exe"
requires_wine = true
supported_loggers = []
sha256 = "82136f219ef61cf7cb14d5ff02e67e4777d1e52bf46b2fca45d52cf146f69820"

[compilers.cr2compv0-2-01]
description = "Campbell Scientific Compiler (cr2compv0.2.01.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv0-2-01.zip"
executable_name = "cr2compv0.2.01.exe"
requires_wine = true
supported_loggers = []
sha256 = "36f6fefc08a6aea8b0e9b3f8f149102698199d1235a92b659c85a685c514e554"

[compilers.cr2compv02]
description = "Campbell Scientific Compiler (cr2compv02.exe)"
version = "v02"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv02.zip"
executable_name = "cr2compv02.exe"
requires_wine = true
supported_loggers = []
sha256 = "2335b66ea319538f49e1931ec2c5d5ec5668f0cf1c63c28b7076b5132a5ef7d0"

[compilers.cr2compv03a]
description = "Campbell Scientific Compiler (cr2compv03A.exe)"
version = "v03a"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv03a.zip"
executable_name = "cr2compv03A.exe"
requires_wine = true
supported_loggers = []
sha256 = "e17e268bf8f2b375af03eb9ea3f541ecb8be6ae1185c758222480489874ca1dc"

[compilers.cr2compv04]
description = "Campbell Scientific Compiler (cr2compv04.exe)"
version = "v04"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv04.zip"
executable_name = "cr2compv04.exe"
requires_wine = true
supported_loggers = []
sha256 = "8dca89f1e7114d8211a7c03069b5c514ed5cf5a49e1f5d12c8e2974296bac6eb"

[compilers.cr2compv04g]
description = "Campbell Scientific Compiler (cr2compv04G.exe)"
version = "v04g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv04g.zip"
executable_name = "cr2compv04G.exe"
requires_wine = true
supported_loggers = []
sha256 = "136286daf21588f43f1298ddd7763587b74b31c0759b63b06d41e80e8f179b47"

[compilers.cr2compv05]
description = "Campbell Scientific Compiler (cr2compv05.exe)"
version = "v05"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv05.zip"
executable_name = "cr2compv05.exe"
requires_wine = true
supported_loggers = []
sha256 = "e90ebca144f3c1c0b29368632611a2afe036166f258356cd8e7b1972af065564"

[compilers.cr2compv06]
description = "Campbell Scientific Compiler (cr2compv06.exe)"
version = "v06"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv06.zip"
executable_name = "cr2compv06.exe"
requires_wine = true
supported_loggers = []
sha256 = "ac371aaa93cf055781a94efa7b87bb156f68653afa8283e1bd9d74ac3a56b5de"

[compilers.cr2compv06g]
description = "Campbell Scientific Compiler (cr2compv06G.exe)"
version = "v06g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv06g.zip"
executable_name = "cr2compv06G.exe"
requires_wine = true
supported_loggers = []
sha256 = "1e5da288a79a4a04104980ee4aa3bc79f361cc87a9deac0adf3a7406c8b8d972"

[compilers.cr2compv06s]
description = "Campbell Scientific Compiler (cr2compv06S.exe)"
version = "v06s"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv06s.zip"
executable_name = "cr2compv06S.exe"
requires_wine = true
supported_loggers = []
sha256 = "803250912e6ba9720a70623f01bc745fe1b079cbbc10dc3b6d7e4d66c856342f"

[compilers.cr2compv07]
description = "Campbell Scientific Compiler (cr2compv07.exe)"
version = "v07"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv07.zip"
executable_name = "cr2compv07.exe"
requires_wine = true
supported_loggers = []
sha256 = "2aaf1410546c4f5bf7e6785ee48ed6d308619a65adc0c27fe1c5b32f7459b1bb"

[compilers.cr2compv07g]
description = "Campbell Scientific Compiler (cr2compv07G.exe)"
version = "v07g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv07g.zip"
executable_name = "cr2compv07G.exe"
requires_wine = true
supported_loggers = []
sha256 = "cb669024478553784a6c87a88ac9e468bffa2fb7a7d4e30a0377742832097928"

[compilers.cr2compv07m]
description = "Campbell Scientific Compiler (cr2compv07M.exe)"
version = "v07m"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv07m.zip"
executable_name = "cr2compv07M.exe"
requires_wine = true
supported_loggers = []
sha256 = "b949814aae5731036eead69ff7b742331bb9353dc41bd55ad6c9566f3cdb3994"

[compilers.cr2compv07s]
description = "Campbell Scientific Compiler (cr2compv07S.exe)"
version = "v07s"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv07s.zip"
executable_name = "cr2compv07S.exe"
requires_wine = true
supported_loggers = []
sha256 = "fa00ee1a3ee4e0d3712716beabd6a4a6539baaefac85f25096d6970ff630b5de"

[compilers.cr2compv09]
description = "Campbell Scientific Compiler (cr2compv09.exe)"
version = "v09"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv09.zip"
executable_name = "cr2compv09.exe"
requires_wine = true
supported_loggers = []
sha256 = "dd8fecb1be03e433eeedfaf953a513e53b31ffe6abdbdf487cfe9c1837b0f792"

[compilers.cr2compv09g]
description = "Campbell Scientific Compiler (cr2compv09G.exe)"
version = "v09g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv09g.zip"
executable_name = "cr2compv09G.exe"
requires_wine = true
supported_loggers = []
sha256 = "982bbf0396624187b48d115e7c73dbf46e4b731373476616d708bd98dcf2468b"

[compilers.cr2compv09m]
description = "Campbell Scientific Compiler (cr2compv09M.exe)"
version = "v09m"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv09m.zip"
executable_name = "cr2compv09M.exe"
requires_wine = true
supported_loggers = []
sha256 = "9341c7158871b7e3d1db30fe646ab864dd1f9e74662dc29cebccae5e8957d0b0"

[compilers.cr2compv09s]
description = "Campbell Scientific Compiler (cr2compv09S.exe)"
version = "v09s"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv09s.zip"
executable_name = "cr2compv09S.exe"
requires_wine = true
supported_loggers = []
sha256 = "50b4d7e341dee81efff0ca9337fd34fe2f40466f5fccd4184d48628e0bb90309"

[compilers.cr2compv10]
description = "Campbell Scientific Compiler (cr2compv10.exe)"
version = "v10"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv10.zip"
executable_name = "cr2compv10.exe"
requires_wine = true
supported_loggers = []
sha256 = "4715ee1fc5c151adeaaafcf9e2ac1b2c99472598d28721b6853c0607433eadb8"

[compilers.cr2compv10g]
description = "Campbell Scientific Compiler (cr2compv10G.exe)"
version = "v10g"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv10g.zip"
executable_name = "cr2compv10G.exe"
requires_wine = true
supported_loggers = []
sha256 = "413505257c49ac32029323be156843d31192c8fd3291445b08d3e7d38d607a58"

[compilers.cr2compv10m]
description = "Campbell Scientific Compiler (cr2compv10M.exe)"
version = "v10m"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv10m.zip"
executable_name = "cr2compv10M.exe"
requires_wine = true
supported_loggers = []
sha256 = "5aaac0f87d2e7ab50faeaaa054dc7bfaf9a5f8cf94ab0623024786d3f6641e5a"

[compilers.cr2compv10s]
description = "Campbell Scientific Compiler (cr2compv10S.exe)"
version = "v10s"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr2compv10s.zip"
executable_name = "cr2compv10S.exe"
requires_wine = true
supported_loggers = []
sha256 = "08a66f69d303001935c82b06205de2efb5c51e5da6a88c44de63f14f6e71339a"

[compilers.cr350comp]
description = "Campbell Scientific Compiler (cr350comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr350comp.zip"
executable_name = "cr350comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "2b5cd420a9e1a91468d37a5cec22db9d191516e45233e1a146c480ea95e6f068"

[compilers.cr3comp]
description = "Campbell Scientific Compiler (cr3comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr3comp.zip"
executable_name = "cr3comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "f5ba6eb0160cf3d36e81b7be8d35bbb6c150fd3038417e3c2c20a8ead8073c66"

[compilers.cr8comp]
description = "Campbell Scientific Compiler (cr8comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr8comp.zip"
executable_name = "cr8comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "2b9a2bd2f0652a3657808c2e63ed3080c331d32415fc38c344957ffcaf6d8a82"

[compilers.cr9comp]
description = "Campbell Scientific Compiler (cr9comp.exe)"
version = "standard"
download_url = "https://github.com/RileyLeff/campbell-scientific-compilers/releases/download/2025.05.13.0/cr9comp.zip"
executable_name = "cr9comp.exe"
requires_wine = true
supported_loggers = []
sha256 = "6715428e7a8b1221acf622a9ef5cf206e25b59062445b8493ee8585c42d182c7"
